module.exports = {
  CODE: 200,
  CODE_CREATED: 201,
  ERROR_CODE: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_FORBIDDEN: 403,
  ERROR_NOT_FOUND: 404,
  ERROR_CONFLICT: 409,
  ERROR_INTERNAL_SERVER: 500,
  BADREQUESTDATA: 'Переданы некорректные данные',
  NOTFOUNDMOVIE: 'Фильм не найден',
  MOVIEDElETED: 'Фильм удален',
  CONFLICTEMAIL: 'Адрес электронной почты уже зарегистрирован',
  CONFLICTEMOVIE: 'Фильм уже добавлен',
  NOTFOUNDUSER: 'Пользователь не найден',
  UNAUTHORIZED: 'Необходимо пройти авторизацию',
  BADREQUESTEMAILPASSWORD: 'Неправильно указан электронный адрес или пароль',
  AUTHORIZED: 'Авторизация пройдена',
  NOTFOUNDPAGE: 'По указанному адресу страница не найдена',
  FORBIDDENDELETE: 'Вы не можете удалить карточку другого пользователя',
  SERVERERROR: 'На сервере произошла ошибка',
};
